filter {
  if "webapp" in [tags] {
    if [log_type] == "webapp" and [action] {
      mutate {
        rename => { "user"        => "[user][name]" }
        rename => { "ip"          => "[client][ip]" }
        rename => { "method"      => "[http][request][method]" }
        rename => { "path"        => "[url][path]" }
        rename => { "status_code" => "[http][response][status_code]" }
        rename => { "action"      => "[event][action]" }
        rename => { "outcome"     => "[event][outcome]" }
        rename => { "duration_ms" => "[event][duration]" }
        add_field => { "[event][dataset]" => "webapp" }
      }
      if [event][action] == "login" {
        if [event][outcome] == "success" {
          mutate { add_tag => ["login_success"] }
        } else {
          mutate { add_tag => ["login_failure"] }
        }
      }
    }
  }
}