filter {
  if "syslog" in [tags] or "syslog_udp" in [tags] or "linux_auth" in [tags] {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_ts} %{SYSLOGHOST:host_name} %{DATA:proc}(?:\[%{POSINT:pid}\])?: %{GREEDYDATA:syslog_msg}" }
      overwrite => ["message"]
    }
    date {
      match  => ["syslog_ts", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss"]
      target => "@timestamp"
    }
    mutate {
      rename => { "syslog_msg" => "message" }
      rename => { "proc"       => "[process][name]" }
      rename => { "pid"        => "[process][pid]" }
    }
    if [process][name] in ["sshd","sudo","su","login","passwd"] {
      mutate { add_tag => ["linux_auth"] }
    }
  }
}