filter {
  if [@metadata][beat] == "winlogbeat" {
    mutate { add_tag => ["windows_security"] }
    if [winlog][event_id] == 4624 { mutate { add_tag => ["login_success"] } }
    if [winlog][event_id] == 4625 { mutate { add_tag => ["login_failure"] } }
    if [winlog][event_id] == 4634 { mutate { add_tag => ["logout"] } }
    if [winlog][event_id] == 4647 { mutate { add_tag => ["logout"] } }
    if [winlog][event_id] == 4688 { mutate { add_tag => ["process_creation"] } }
    if [winlog][channel] =~ /PowerShell/ {
      mutate { add_tag => ["powershell"] }
    }
  }
  if [@metadata][beat] == "filebeat" {
    if "docker_log" in [tags] {
      mutate { add_tag => ["docker_log"] }
    }
  }
}