output {
  if "webapp" in [tags] {
    elasticsearch {
      hosts    => ["http://elasticsearch:9200"]
      user     => "logstash_internal"
      password => "${LOGSTASH_INTERNAL_PASSWORD}"
      index    => "webapp-logs-%{+YYYY.MM.dd}"
    }
  } else if "windows_security" in [tags] {
    elasticsearch {
      hosts    => ["http://elasticsearch:9200"]
      user     => "logstash_internal"
      password => "${LOGSTASH_INTERNAL_PASSWORD}"
      index    => "windows-logs-%{+YYYY.MM.dd}"
    }
  } else if "syslog" in [tags] or "linux_auth" in [tags] {
    elasticsearch {
      hosts    => ["http://elasticsearch:9200"]
      user     => "logstash_internal"
      password => "${LOGSTASH_INTERNAL_PASSWORD}"
      index    => "syslog-%{+YYYY.MM.dd}"
    }
  } else if "docker_log" in [tags] {
    elasticsearch {
      hosts    => ["http://elasticsearch:9200"]
      user     => "logstash_internal"
      password => "${LOGSTASH_INTERNAL_PASSWORD}"
      index    => "docker-logs-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts    => ["http://elasticsearch:9200"]
      user     => "logstash_internal"
      password => "${LOGSTASH_INTERNAL_PASSWORD}"
      index    => "misc-logs-%{+YYYY.MM.dd}"
    }
  }
}